### ISSUE TITLE
Parse function configuration file client side

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#32]
`tm` should be able to parse a `serverless.yml` like file that defines the multiple functions a repo, their arguments, runtime etc.

then deploy services for each function

**Comment by tzununbekov** [comment]
In `serverless` branch I pushed several changes that makes possible to deploy multiple functions with `--definition <path>` parameter, but deployment options are very limited now. Here is an example of possible serverless.yaml:

```
service: serverless-test

provider:
  name: triggermesh
  runtime: openfaas-go-runtime

functions:
  hello:
    handler: foo/main.go
  world:
    handler: bar/main.go
``` 


While I was working on that, few questions appeared:
1) Do we need to strictly keep to serverless framework yaml file format and its deployment options?
2) Are we planning to fully support applications that run on serverless framework?
Depending on answers, I'll probably have more questions. 
One of the main concern here is runtimes that we don't support now (aws-lambda for example) and eventing

**Comment by sebgoa** [comment]
nice.

At a high level:

1. We will only support functions that deploy to knative/triggermesh so no need to worry about other targets like AWS.

2. Let's skip eventing in this first iteration

3. If you do `tm deploy` it should by default look for a `serverless.yml` and deploy that. if it does not find it then print an error message. if you specify it at the cli do `tm deploy -f foo.yaml`

Now on to details:

1. The runtime should be a name referencing to an existing build template. Or a URL to a build template. If it is a URL then `tm` should create it. Make sure that you can also set the runtime per function and not only at the provider level.

2. Add memorySize like:

```
provider:
  name: knative
  runtime: https://raw.githubusercontent.com/triggermesh/openfaas-runtime/master/go/openfaas-go-runtime.yaml
  memorySize: 512 
```
This should set a resources limit in the Configuration spec...which becomes a resource limit in the underlying Pod.

3. Add 'description' field for functions. This should become an annotation set in the metadata

4. Add 'labels' which become labels in the metadata

5. Add 'environment' which is a list of environment variables.

see: https://github.com/serverless/examples/blob/master/aws-node-env-variables/serverless.yml

6. Add support for multiple functions in an array like

```
# Multiple functions

functions:
  - ${file(../foo-functions.yml)}
  - ${file(../bar-functions.yml)}
```
