### ISSUE TITLE
implement _deploy_ command

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#4]
we should be able to deploy a container as a Service object in knative.

```
tm deploy foo --from-image gcr.io/knative-samples/helloworld-go
```

will create the following object:

```
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: foo # The name of the app
  namespace: default # The namespace the app will use
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
            env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
```
