### ISSUE TITLE
Specify cronjob in manifest

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#71]
To follow the serverless framework, we should be able to parse a scheduled `event` described in the manifest and create a corresponding CronJob source.

See:
https://github.com/knative/eventing-sources/blob/master/samples/cronjob-source/source.yaml

And:
https://github.com/sebgoa/lambda-google-sheets/blob/master/serverless.yml#L62

It will allow us to schedule function execution.

**Comment by sebgoa** [comment]
tested it with a local KLR go function and:

```
service: serverless-foo
description: "cron test with KLR"

provider:
  name: triggermesh

functions:
  goklr:
    source: main.go
    runtime: https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/go-1.x/buildtemplate.yaml 
    description: "klr go"
    environment:
      FUNCTION: go-klr
    events:
     - schedule:
         rate: "*/1 * * * *"
         data: '{"Name":"sebgoa"}'
```

happy to close this, it works well. The events section ends up creating a CronJob source.
