### ISSUE TITLE
build argument not honored

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#75]
I tried to create a service with an image that should go to my Docker hub account like:

```
tm deploy service python-test -f . \
                              --build-template knative-python37-runtime \
                              --build-argument IMAGE=index.docker.io/runseb/python-test
                              --build-argument HANDLER=handler.endpoint \
                              --wait
```

The build manifest ended up with:

```
  template:
        arguments:
            - {name: IMAGE, value: knative.registry.svc.cluster.local/sebgoa-python-test}
            - {name: IMAGE, value: index.docker.io/runseb/python-test}
        kind: BuildTemplate
        name: knative-python37-runtime
```
